"""Pre-built method templates for common compound classes."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class MethodTemplate:
    id: str
    name: str
    category: str
    description: str
    column_type: str
    mobile_phase_a: str
    mobile_phase_b: str
    additive: str
    ph: float
    percent_b_start: float
    percent_b_end: float
    gradient_time_min: float
    flow_rate_ml_min: float
    temperature_c: float
    column_length_mm: int
    particle_size_um: float


_TEMPLATES: list[MethodTemplate] = [
    MethodTemplate(
        id="pharma-small-mol",
        name="Pharmaceuticals (Small Molecules)",
        category="Pharmaceuticals",
        description="Reversed-phase C18 method for small molecule drugs (MW 150-600). Broad gradient covering most drug-like compounds.",
        column_type="C18",
        mobile_phase_a="Water + 0.1% Formic Acid",
        mobile_phase_b="Acetonitrile",
        additive="0.1% Formic Acid",
        ph=2.7,
        percent_b_start=5,
        percent_b_end=95,
        gradient_time_min=20,
        flow_rate_ml_min=0.4,
        temperature_c=40,
        column_length_mm=100,
        particle_size_um=1.7,
    ),
    MethodTemplate(
        id="peptides",
        name="Peptides",
        category="Biomolecules",
        description="C18 method optimized for peptides and small proteins. Shallow gradient with TFA for sharp peaks.",
        column_type="C18",
        mobile_phase_a="Water + 0.1% TFA",
        mobile_phase_b="Acetonitrile + 0.1% TFA",
        additive="0.1% TFA",
        ph=2.2,
        percent_b_start=5,
        percent_b_end=40,
        gradient_time_min=60,
        flow_rate_ml_min=0.3,
        temperature_c=45,
        column_length_mm=150,
        particle_size_um=1.8,
    ),
    MethodTemplate(
        id="metabolites-polar",
        name="Polar Metabolites",
        category="Metabolomics",
        description="HILIC method for highly polar metabolites, sugars, nucleotides. High organic start for proper HILIC retention.",
        column_type="HILIC",
        mobile_phase_a="10mM Ammonium Bicarbonate (pH 9.0)",
        mobile_phase_b="Acetonitrile",
        additive="10mM Ammonium Bicarbonate",
        ph=9.0,
        percent_b_start=90,
        percent_b_end=50,
        gradient_time_min=15,
        flow_rate_ml_min=0.4,
        temperature_c=30,
        column_length_mm=100,
        particle_size_um=2.6,
    ),
    MethodTemplate(
        id="pesticides-multiresidue",
        name="Pesticides (Multi-residue)",
        category="Environmental",
        description="C18 multi-residue pesticide screening. Wide gradient for diverse polarity range of pesticides.",
        column_type="C18",
        mobile_phase_a="Water + 5mM Ammonium Formate",
        mobile_phase_b="Methanol",
        additive="5mM Ammonium Formate",
        ph=3.0,
        percent_b_start=10,
        percent_b_end=95,
        gradient_time_min=25,
        flow_rate_ml_min=0.4,
        temperature_c=40,
        column_length_mm=100,
        particle_size_um=1.8,
    ),
    MethodTemplate(
        id="proteins-large",
        name="Proteins (Large)",
        category="Biomolecules",
        description="C4 wide-pore method for large proteins and antibodies. Lower %B range for hydrophobic large molecules.",
        column_type="C18",
        mobile_phase_a="Water + 0.1% TFA",
        mobile_phase_b="Acetonitrile + 0.1% TFA",
        additive="0.1% TFA",
        ph=2.7,
        percent_b_start=20,
        percent_b_end=70,
        gradient_time_min=30,
        flow_rate_ml_min=0.3,
        temperature_c=60,
        column_length_mm=100,
        particle_size_um=3.0,
    ),
    MethodTemplate(
        id="sugars-saccharides",
        name="Sugars & Saccharides",
        category="Food & Beverage",
        description="HILIC method for carbohydrates and sugars. Ammonium acetate buffer for neutral sugar analysis.",
        column_type="HILIC",
        mobile_phase_a="10mM Ammonium Acetate (pH 7.0)",
        mobile_phase_b="Acetonitrile",
        additive="10mM Ammonium Acetate",
        ph=7.0,
        percent_b_start=85,
        percent_b_end=40,
        gradient_time_min=20,
        flow_rate_ml_min=0.4,
        temperature_c=30,
        column_length_mm=150,
        particle_size_um=2.6,
    ),
    MethodTemplate(
        id="aromatics-phenyl",
        name="Aromatics & PAHs",
        category="Environmental",
        description="Phenyl column for aromatic selectivity. Pi-pi interactions for PAHs and aromatic compounds.",
        column_type="phenyl",
        mobile_phase_a="Water + 0.1% Formic Acid",
        mobile_phase_b="Acetonitrile",
        additive="0.1% Formic Acid",
        ph=3.0,
        percent_b_start=20,
        percent_b_end=95,
        gradient_time_min=25,
        flow_rate_ml_min=0.4,
        temperature_c=35,
        column_length_mm=100,
        particle_size_um=2.6,
    ),
    MethodTemplate(
        id="ionizable-bases",
        name="Ionizable Bases (Amines)",
        category="Pharmaceuticals",
        description="C18 at acidic pH with ion-pair alternative. Good for basic compounds with high pKa.",
        column_type="C18",
        mobile_phase_a="Water + 0.1% Formic Acid + 5mM Ammonium Formate",
        mobile_phase_b="Acetonitrile",
        additive="0.1% Formic Acid + 5mM Ammonium Formate",
        ph=3.5,
        percent_b_start=5,
        percent_b_end=80,
        gradient_time_min=22,
        flow_rate_ml_min=0.4,
        temperature_c=45,
        column_length_mm=100,
        particle_size_um=1.8,
    ),
    MethodTemplate(
        id="ion-pair-surfactants",
        name="Ion-Pair (Surfactants/Ions)",
        category="Specialty",
        description="Ion-pair chromatography for permanently charged compounds. TFA or PFPA as ion-pair reagent.",
        column_type="ion_pair",
        mobile_phase_a="Water + 5mM TFA",
        mobile_phase_b="Acetonitrile + 5mM TFA",
        additive="5mM TFA",
        ph=2.5,
        percent_b_start=20,
        percent_b_end=80,
        gradient_time_min=30,
        flow_rate_ml_min=0.3,
        temperature_c=35,
        column_length_mm=150,
        particle_size_um=3.0,
    ),
    MethodTemplate(
        id="fast-screening",
        name="Fast Screening (5 min)",
        category="High-Throughput",
        description="Rapid 5-minute gradient for high-throughput screening. Short column, high flow rate.",
        column_type="C18",
        mobile_phase_a="Water + 0.1% Formic Acid",
        mobile_phase_b="Acetonitrile",
        additive="0.1% Formic Acid",
        ph=2.7,
        percent_b_start=5,
        percent_b_end=95,
        gradient_time_min=5,
        flow_rate_ml_min=0.6,
        temperature_c=50,
        column_length_mm=50,
        particle_size_um=1.7,
    ),
    # ============================================================
    # Metabolomics — based on published LC-MS methods
    # ============================================================
    MethodTemplate(
        id="metabolomics-rp-hss-t3",
        name="Untargeted Metabolomics (RP)",
        category="Metabolomics",
        description="Reversed-phase untargeted metabolomics using Waters HSS T3 column. Covers medium-polarity metabolites, organic acids, acylcarnitines, biogenic amines. Based on widely cited HILIC+RPLC dual-platform workflows (Cajka & Fiehn, 2016).",
        column_type="C18",
        mobile_phase_a="Water + 0.1% Formic Acid + 5mM Ammonium Formate",
        mobile_phase_b="Acetonitrile + 0.1% Formic Acid",
        additive="0.1% Formic Acid + 5mM Ammonium Formate",
        ph=3.0,
        percent_b_start=0,
        percent_b_end=100,
        gradient_time_min=18,
        flow_rate_ml_min=0.4,
        temperature_c=40,
        column_length_mm=100,
        particle_size_um=1.8,
    ),
    MethodTemplate(
        id="metabolomics-hilic-beh-amide",
        name="Polar Metabolomics (HILIC Amide)",
        category="Metabolomics",
        description="HILIC method for polar metabolites using Waters BEH Amide column. Covers amino acids, sugars, nucleotides, sugar phosphates, acylcarnitines. Mobile phase: 10mM ammonium formate + 0.125% formic acid in ACN/water. Based on EMBL-MCF and Cajka/Fiehn published methods.",
        column_type="HILIC",
        mobile_phase_a="10mM Ammonium Formate + 0.125% Formic Acid in Water (pH 3.0)",
        mobile_phase_b="10mM Ammonium Formate + 0.125% Formic Acid in ACN (95:5 ACN:Water)",
        additive="10mM Ammonium Formate + 0.125% Formic Acid",
        ph=3.0,
        percent_b_start=95,
        percent_b_end=60,
        gradient_time_min=15,
        flow_rate_ml_min=0.4,
        temperature_c=40,
        column_length_mm=100,
        particle_size_um=1.7,
    ),
    MethodTemplate(
        id="metabolomics-hilic-z-high-ph",
        name="Polar Metabolomics (HILIC-Z High pH)",
        category="Metabolomics",
        description="High-pH HILIC method for organic acids, sugar phosphates, nucleotides, CoA derivatives. Uses Agilent Poroshell HILIC-Z column with 10mM ammonium acetate pH 9.0. Negative ion mode optimized. Based on Agilent Discovery Metabolomics application note.",
        column_type="HILIC",
        mobile_phase_a="10mM Ammonium Acetate (pH 9.0, adjusted with NH4OH) in 90:10 Water:ACN",
        mobile_phase_b="10mM Ammonium Acetate (pH 9.0) in 90:10 ACN:Water",
        additive="10mM Ammonium Acetate (pH 9.0)",
        ph=9.0,
        percent_b_start=95,
        percent_b_end=50,
        gradient_time_min=20,
        flow_rate_ml_min=0.3,
        temperature_c=35,
        column_length_mm=150,
        particle_size_um=2.7,
    ),
    MethodTemplate(
        id="metabolomics-rp-organic-acids",
        name="Organic Acids (RP Formic Acid)",
        category="Metabolomics",
        description="Reversed-phase method optimized for organic acids using 0.1% formic acid. Best ESI+ signal for organic acids per optimization studies (IJMS 2023, 24, 1987). C18 column with shallow gradient.",
        column_type="C18",
        mobile_phase_a="Water + 0.1% Formic Acid",
        mobile_phase_b="Acetonitrile + 0.1% Formic Acid",
        additive="0.1% Formic Acid",
        ph=2.7,
        percent_b_start=2,
        percent_b_end=60,
        gradient_time_min=12,
        flow_rate_ml_min=0.35,
        temperature_c=35,
        column_length_mm=100,
        particle_size_um=1.8,
    ),
    # ============================================================
    # Lipidomics — based on published LC-MS methods
    # ============================================================
    MethodTemplate(
        id="lipidomics-rp-csh-c18",
        name="Untargeted Lipidomics (RP CSH C18)",
        category="Lipidomics",
        description="High-throughput reversed-phase lipidomics using Waters CSH C18 column. Covers 20+ lipid subclasses (TG, DG, PC, PE, PI, PS, PA, PG, Cer, SM, ChE, LPC, LPE). Mobile phase: ACN/Water/IPA with 10mM ammonium formate + 0.1% formic acid. Based on Waters application note (2020) and Cajka & Fiehn (2016). 12-min method for large cohort studies.",
        column_type="C18",
        mobile_phase_a="60:30:10 ACN:Water:1M Ammonium Formate in 0.1% Formic Acid",
        mobile_phase_b="90:9:1 IPA:ACN:1M Ammonium Formate in 0.1% Formic Acid",
        additive="10mM Ammonium Formate + 0.1% Formic Acid",
        ph=3.0,
        percent_b_start=10,
        percent_b_end=100,
        gradient_time_min=12,
        flow_rate_ml_min=0.4,
        temperature_c=55,
        column_length_mm=100,
        particle_size_um=1.7,
    ),
    MethodTemplate(
        id="lipidomics-rp-beh-c18-quant",
        name="Targeted Lipidomics (BEH C18 Quant)",
        category="Lipidomics",
        description="Quantitative targeted lipidomics using Waters BEH C18 column at 60°C. Covers 1163 lipid species across 20 subclasses with stable isotope internal standards. Mobile phase: Water/ACN/IPA with 10mM ammonium acetate. Based on comprehensive lipidomic workflow (J Proteome Res, 2023). 15-min cycle for high-throughput quantitation.",
        column_type="C18",
        mobile_phase_a="50:30:20 Water:ACN:Isopropanol + 10mM Ammonium Acetate",
        mobile_phase_b="90:9:1 Isopropanol:ACN:Water + 10mM Ammonium Acetate",
        additive="10mM Ammonium Acetate",
        ph=7.0,
        percent_b_start=10,
        percent_b_end=100,
        gradient_time_min=15,
        flow_rate_ml_min=0.4,
        temperature_c=60,
        column_length_mm=100,
        particle_size_um=1.7,
    ),
    MethodTemplate(
        id="lipidomics-rp-neg-mode",
        name="Lipidomics (Negative ESI Mode)",
        category="Lipidomics",
        description="Reversed-phase lipidomics optimized for ESI negative mode. Uses 10mM ammonium acetate + 0.1% acetic acid for robust retention and signal of phospholipids, free fatty acids, and sulfatides. Based on mobile phase optimization studies (IJMS 2023).",
        column_type="C18",
        mobile_phase_a="60:30:10 ACN:Water:1M Ammonium Acetate + 0.1% Acetic Acid",
        mobile_phase_b="90:9:1 IPA:ACN:1M Ammonium Acetate + 0.1% Acetic Acid",
        additive="10mM Ammonium Acetate + 0.1% Acetic Acid",
        ph=5.5,
        percent_b_start=10,
        percent_b_end=100,
        gradient_time_min=20,
        flow_rate_ml_min=0.4,
        temperature_c=50,
        column_length_mm=100,
        particle_size_um=1.7,
    ),
    MethodTemplate(
        id="lipidomics-c30-carotenoids",
        name="Carotenoids & Fat-Soluble Vitamins (C30)",
        category="Lipidomics",
        description="C30 column method for carotenoids, retinoids, tocopherols, and vitamin D isomers. Shape-selective separation of geometric isomers. Uses Accucore C30 with methanol/MTBE gradient.",
        column_type="C30",
        mobile_phase_a="Water + 0.1% Formic Acid",
        mobile_phase_b="Methanol:MTBE (80:20) + 0.1% Formic Acid",
        additive="0.1% Formic Acid",
        ph=2.7,
        percent_b_start=80,
        percent_b_end=100,
        gradient_time_min=25,
        flow_rate_ml_min=0.3,
        temperature_c=35,
        column_length_mm=150,
        particle_size_um=2.6,
    ),
    # ============================================================
    # Clinical / Toxicology
    # ============================================================
    MethodTemplate(
        id="clinical-tox-screening",
        name="Clinical Toxicology Screening",
        category="Clinical",
        description="Broad drug screening for clinical toxicology. C18 column with acidic mobile phase covering drugs of abuse, prescription drugs, and metabolites. Fast 10-min gradient.",
        column_type="C18",
        mobile_phase_a="Water + 0.1% Formic Acid + 2mM Ammonium Formate",
        mobile_phase_b="Acetonitrile + 0.1% Formic Acid",
        additive="0.1% Formic Acid + 2mM Ammonium Formate",
        ph=3.0,
        percent_b_start=5,
        percent_b_end=95,
        gradient_time_min=10,
        flow_rate_ml_min=0.5,
        temperature_c=45,
        column_length_mm=100,
        particle_size_um=2.6,
    ),
    MethodTemplate(
        id="therapeutic-drug-monitoring",
        name="Therapeutic Drug Monitoring (TDM)",
        category="Clinical",
        description="Therapeutic drug monitoring for immunosuppressants (tacrolimus, cyclosporine, sirolimus) and anti-epileptics. C18 with 0.1% formic acid, positive ESI mode.",
        column_type="C18",
        mobile_phase_a="Water + 0.1% Formic Acid + 2mM Ammonium Formate",
        mobile_phase_b="Methanol + 0.1% Formic Acid",
        additive="0.1% Formic Acid + 2mM Ammonium Formate",
        ph=3.0,
        percent_b_start=30,
        percent_b_end=90,
        gradient_time_min=8,
        flow_rate_ml_min=0.4,
        temperature_c=50,
        column_length_mm=50,
        particle_size_um=1.8,
    ),
]


def list_templates(category: str | None = None) -> list[MethodTemplate]:
    if category:
        return [t for t in _TEMPLATES if t.category == category]
    return _TEMPLATES


def get_template(template_id: str) -> MethodTemplate | None:
    for t in _TEMPLATES:
        if t.id == template_id:
            return t
    return None


def get_categories() -> list[str]:
    return sorted({t.category for t in _TEMPLATES})


def template_to_dict(t: MethodTemplate) -> dict[str, Any]:
    return {
        "id": t.id,
        "name": t.name,
        "category": t.category,
        "description": t.description,
        "column_type": t.column_type,
        "mobile_phase_a": t.mobile_phase_a,
        "mobile_phase_b": t.mobile_phase_b,
        "additive": t.additive,
        "ph": t.ph,
        "percent_b_start": t.percent_b_start,
        "percent_b_end": t.percent_b_end,
        "gradient_time_min": t.gradient_time_min,
        "flow_rate_ml_min": t.flow_rate_ml_min,
        "temperature_c": t.temperature_c,
        "column_length_mm": t.column_length_mm,
        "particle_size_um": t.particle_size_um,
    }


def template_to_gradient_table(t: MethodTemplate) -> list[dict[str, float]]:
    """Convert template to a gradient table."""
    t_total = t.gradient_time_min * 60
    return [
        {"time_s": 0, "percent_b": t.percent_b_start},
        {"time_s": 60, "percent_b": t.percent_b_start},
        {"time_s": t_total - 120, "percent_b": t.percent_b_end},
        {"time_s": t_total, "percent_b": t.percent_b_end},
    ]
